
import java.awt.Color;
public class JovoDaVelha extends javax.swing.JFrame {

    private int jogador = 0; //0 = 0 e X = 1
    private int jogo[][] = new int[3][3];
    
    /**
     * Creates new form JovoDaVelha
     */
    public JovoDaVelha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt1 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        btReiniciar = new javax.swing.JButton();
        txMensagem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt1.setBackground(new java.awt.Color(255, 255, 255));
        bt1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        bt1.setForeground(new java.awt.Color(0, 0, 153));
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt4.setBackground(new java.awt.Color(255, 255, 255));
        bt4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        bt4.setForeground(new java.awt.Color(255, 0, 0));
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });

        bt7.setBackground(new java.awt.Color(255, 255, 255));
        bt7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        bt7.setForeground(new java.awt.Color(0, 0, 153));
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });

        bt2.setBackground(new java.awt.Color(255, 255, 255));
        bt2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        bt2.setForeground(new java.awt.Color(255, 0, 0));
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        bt5.setBackground(new java.awt.Color(255, 255, 255));
        bt5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        bt5.setForeground(new java.awt.Color(0, 0, 153));
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });

        bt8.setBackground(new java.awt.Color(255, 255, 255));
        bt8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        bt8.setForeground(new java.awt.Color(255, 0, 0));
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });

        bt3.setBackground(new java.awt.Color(255, 255, 255));
        bt3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        bt3.setForeground(new java.awt.Color(0, 0, 153));
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        bt6.setBackground(new java.awt.Color(255, 255, 255));
        bt6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        bt6.setForeground(new java.awt.Color(255, 0, 0));
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });

        bt9.setBackground(new java.awt.Color(255, 255, 255));
        bt9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        bt9.setForeground(new java.awt.Color(0, 0, 153));
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });

        btReiniciar.setBackground(new java.awt.Color(0, 255, 204));
        btReiniciar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btReiniciar.setForeground(new java.awt.Color(0, 51, 51));
        btReiniciar.setText("Reiniciar");
        btReiniciar.setBorder(new javax.swing.border.MatteBorder(null));
        btReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReiniciarActionPerformed(evt);
            }
        });

        txMensagem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txMensagem.setForeground(new java.awt.Color(0, 102, 51));
        txMensagem.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(txMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
        if(jogador == 0){
          bt1.setText("0");
          //bt1.setForeground(Color.BLUE);
          jogo[0][0] = 0;
          jogador = 'X';
        }else{
           bt1.setText("X"); 
           jogo[0][0] = 1;
           jogador = 0;
        }
        bt1.setEnabled(false);
        txMensagem.setText("É a vez do jogador " + jogador);
        verificaJogada();
        
        
    }//GEN-LAST:event_bt1ActionPerformed

    private void btReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReiniciarActionPerformed
        // TODO add your handling code here:
        
        //reseta botoes
        bt1.setEnabled(true);
        bt1.setText("");
        bt2.setEnabled(true);
        bt2.setText("");     
        bt3.setEnabled(true);
        bt3.setText("");   
        bt4.setEnabled(true);
        bt4.setText("");
        bt5.setEnabled(true);
        bt5.setText("");
        bt6.setEnabled(true);
        bt6.setText("");
        bt7.setEnabled(true);
        bt7.setText("");
        bt8.setEnabled(true);
        bt8.setText("");
        bt9.setEnabled(true);
        bt9.setText("");        
        txMensagem.setText("É a vez do jogador " + jogador);
        
        //Reinicia matriz
        for(int i=0;i<3;i++){
            for(int j=0;j <3; j++){
                jogo[i][j] = -1;
            }
        }
        
        
    }//GEN-LAST:event_btReiniciarActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
        if(jogador == 0){
          bt2.setText("0");
          jogo[0][1] = 0;          
          jogador = 1;
        }else{
           bt2.setText("X"); 
          jogo[0][1] = 1;             
           jogador = 0;
        }
        bt2.setEnabled(false);
        txMensagem.setText("É a vez do jogador " + jogador);
        verificaJogada();
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        if(jogador == 0){
          bt3.setText("0");
          jogo[0][2] = 0;            
          jogador = 1;
        }else{
           bt3.setText("X"); 
           jogo[0][2] = 1;  
           jogador = 0;
        }
        bt3.setEnabled(false);
        txMensagem.setText("É a vez do jogador " + jogador);   
        verificaJogada();
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        // TODO add your handling code here:
        if(jogador == 0){
          bt4.setText("0");
          jogo[1][0] = 0;  
          jogador = 1;
        }else{
           bt4.setText("X"); 
          jogo[1][0] = 1;            
           jogador = 0;
        }
        bt4.setEnabled(false);
        txMensagem.setText("É a vez do jogador " + jogador);
        verificaJogada();
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        // TODO add your handling code here:
        if(jogador == 0){
          bt5.setText("0");
          jogo[1][1] = 0;           
          jogador = 1;
        }else{
           bt5.setText("X"); 
           jogo[1][1] = 1;              
           jogador = 0;
        }
        bt5.setEnabled(false);
        txMensagem.setText("É a vez do jogador " + jogador);  
        verificaJogada();
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        // TODO add your handling code here:
        if(jogador == 0){
          bt6.setText("0");
          jogo[1][2] = 0;             
          jogador = 1;
        }else{
           bt6.setText("X"); 
          jogo[1][2] = 1;               
           jogador = 0;
        }
        bt6.setEnabled(false);
        txMensagem.setText("É a vez do jogador " + jogador); 
        verificaJogada();
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        // TODO add your handling code here:
        if(jogador == 0){
          bt7.setText("0");
          jogo[2][0] = 0;              
          jogador = 1;
        }else{
           bt7.setText("X");
          jogo[2][0] = 1;             
           jogador = 0;
        }
        bt7.setEnabled(false);
        txMensagem.setText("É a vez do jogador " + jogador); 
        verificaJogada();
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        
        // TODO add your handling code here:
        if(jogador == 0){
          bt8.setText("0");
          jogo[2][1] = 0;            
          jogador = 1;
        }else{
           bt8.setText("X");
           jogo[2][1] = 1;
           jogador = 0;
        }
        bt8.setEnabled(false);
        txMensagem.setText("É a vez do jogador " + jogador);    
        verificaJogada();
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        // TODO add your handling code here:
        if(jogador == 0){
          bt9.setText("0");
          jogo[2][2] = 0;
          jogador = 1;
        }else{
           bt9.setText("X");
           jogo[2][2] = 1;
           jogador = 0;
        }
        bt9.setEnabled(false);
        txMensagem.setText("É a vez do jogador " + jogador); 
        verificaJogada();
    }//GEN-LAST:event_bt9ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void verificaJogada(){
              
    if(
       (jogo[0][0] == 0 && jogo[0][1] == 0 && jogo[0][2] == 0) ||
       (jogo[1][0] == 0 && jogo[1][1] == 0 && jogo[1][2] == 0) ||
       (jogo[2][0] == 0 && jogo[2][1] == 0 && jogo[2][2] == 0) ||
       (jogo[0][0] == 0 && jogo[1][0] == 0 && jogo[2][0] == 0) ||
       (jogo[0][1] == 0 && jogo[1][1] == 0 && jogo[2][1] == 0) ||
       (jogo[0][2] == 0 && jogo[1][2] == 0 && jogo[2][2] == 0) || 
       (jogo[0][0] == 0 && jogo[1][1] == 0 && jogo[2][2] == 0) ||
       (jogo[0][2] == 0 && jogo[1][1] == 0 && jogo[2][0] == 0)){
            txMensagem.setText("O jogador 0 ganho!!!");
    }else if(
        (jogo[0][0] == 1 && jogo[0][1] == 1 && jogo[0][2] == 1) ||
        (jogo[1][0] == 1 && jogo[1][1] == 1 && jogo[1][2] == 1) ||
        (jogo[2][0] == 1 && jogo[2][1] == 1 && jogo[2][2] == 1) ||
        (jogo[0][0] == 1 && jogo[1][0] == 1 && jogo[2][0] == 1) ||
        (jogo[0][1] == 1 && jogo[1][1] == 1 && jogo[2][1] == 1) ||
        (jogo[0][2] == 1 && jogo[1][2] == 1 && jogo[2][2] == 1) || 
        (jogo[0][0] == 1 && jogo[1][1] == 1 && jogo[2][2] == 1) ||
        (jogo[0][2] == 1 && jogo[1][1] == 1 && jogo[2][0] == 1)){
            txMensagem.setText("O jogador X ganho!!!");
    }
    }
        
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JovoDaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JovoDaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JovoDaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JovoDaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JovoDaVelha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btReiniciar;
    private javax.swing.JTextField txMensagem;
    // End of variables declaration//GEN-END:variables
}
